version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: tst_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: ./backend
    container_name: tst_api
    depends_on:
      redis:
        condition: service_started
    environment:
      REDIS_URL: redis://redis:6379
      JWT_SECRET: tst_super_secret_jwt_2026
      JWT_REFRESH_SECRET: tst_refresh_secret_jwt_2026
      PORT: 3001
      NODE_ENV: development
      STRIPE_SECRET_KEY: sk_test_placeholder
      MPESA_CONSUMER_KEY: placeholder
      MPESA_CONSUMER_SECRET: placeholder
      SENDGRID_API_KEY: SG.placeholder
      FRONTEND_URL: http://localhost:3000
      ADMIN_URL: http://localhost:3002
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules

  website:
    build: ./website
    container_name: tst_website
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/v1
    ports:
      - "3000:3000"
    volumes:
      - ./website:/app
      - /app/node_modules

  admin:
    build: ./admin
    container_name: tst_admin
    depends_on:
      - api
    environment:
      VITE_API_URL: http://localhost:3001/v1
    ports:
      - "3002:3002"
    volumes:
      - ./admin:/app
      - /app/node_modules

volumes:
  redis_data:
